
services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: agarwal
      MYSQL_PASSWORD: pratishtha
      MYSQL_DATABASE: mydb
      MYSQL_USER: pa

  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on: 
      - dbos
    ports:
      - 8088:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: pa
      WORDPRESS_DB_PASSWORD: pratishtha
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wp_storage_new:/var/www/html

volumes:
  joomla_storage:
  mysql_storage:
